### GET request to example server
GET http://localhost:8081/api/favorite

###
POST http://localhost:8081/api/favorite
Content-Type: application/json

{
    "userId":5,
    "courseId": 5476
}

###
DELETE http://localhost:8081/api/favorite/6821d5a67e0ca831e9a59fd3

###
GET http://localhost:8081/api/favorite/check?userId=5&courseId=456

###
GET http://localhost:8081/api/favorite/getByUser?userId=5